
           
       pipeline {
    agent any

    environment {
        CI = 'true'
    }

    stages {
        stage('Install Dependencies in Docker') {
            steps {
                // Check for latest Node.js: https://hub.docker.com/_/node/tags
                sh '''
                docker run --rm -v $PWD:/app -w /app node:18-alpine sh -c "\
                  npm ci --cache /tmp/empty-cache || (rm -rf node_modules package-lock.json && npm install --cache /tmp/empty-cache)"
                '''
            }
        }

        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }

        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
